version: '3.8'

services:
  # Production application
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.local
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
